vpath marked-files-out.% ../marked-files-out
vpath libmarked-files-out.a ../marked-files-out

libmarked-files-out.a: marked-files-out.o

include ../marked-files-out/marked-files-out.d

LIBS += libmarked-files-out.a
